name: Build Windows (Tauri v2)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Expand project from zip
        shell: pwsh
        run: |
          if (Test-Path src) { Remove-Item -Recurse -Force src }
          if (Test-Path src-tauri) { Remove-Item -Recurse -Force src-tauri }
          Expand-Archive -Path dynasty-desktop.zip -DestinationPath . -Force

      - name: Fix Tauri v2 identifier (top-level only)
        shell: pwsh
        run: >
          node -e "const fs=require('fs'),p='src-tauri/tauri.conf.json';
          const j=JSON.parse(fs.readFileSync(p,'utf8'));
          if(!j.identifier) j.identifier='com.dynastydesktop.app';
          if(j.bundle && 'identifier' in j.bundle){ delete j.bundle.identifier }
          fs.writeFileSync(p, JSON.stringify(j,null,2)); console.log('identifier:', j.identifier)"

      - name: Install deps
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm i }

      - name: Build (portable .exe)
        run: npx --yes @tauri-apps/cli@latest build --bundles app

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: tauri-bundle
          path: src-tauri/target/release/bundle/**/*
